config/routes.rb
Rails.application.routes.draw do
  root 'app_pages#home'
  post '/start', to: 'buyers#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/create_daily_tracker', to: 'daily_trackers#create'

  resources :buyers do
  		resources :daily_trackers, only: [:index, :create]
  		resources :buyer_session, only: [:index, :create]
 	end

  resources :nutrition101s
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < ApplicationRecord
	before_save { email.downcase! }
    has_many :daily_trackers, dependent: :destroy
    has_many :buyer_sessions, dependent: :destroy
	validates :username,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    def Buyer.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
    end
end

app/models/buyer_session.rb
class BuyerSession < ApplicationRecord
  belongs_to :buyer
end

app/models/daily_tracker.rb
class DailyTracker < ApplicationRecord
  belongs_to :buyer
  validates :buyer_id, presence: true
  validates :dayNumber, presence: true
  validates :dailyCheckIn, presence: true
  validates :dailyReportedMealPercentage, presence: true
end

app/models/nutrition101.rb
class Nutrition101 < ApplicationRecord
end

app/models/overseer.rb
class Overseer < ApplicationRecord
	before_save{username.downcase!}
	has_secure_password
	 validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/app_pages_controller.rb
class AppPagesController < ApplicationController
  def home
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  	include SessionsHelper
end

app/controllers/buyer_sessions_controller.rb
class BuyerSessionsController < ApplicationController
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
	def index
		@buyers = Buyers.all
	end

	def show
		@buyer = Buyer.find(params[:id])
		@nutrition = Nutrition101.all
	end

	def create 
		@buyer = Buyer.new(buyer_params)
		@buyer.first_signup = true
		@buyer.new_session = true
		@buyer.session_num = 0
		if @buyer.save
			#handle saving registreation data
			log_in @buyer
			flash[:success] = "Welcome to your Dashboard"
			redirect_to @buyer
		else 
			redirect_to root_url
		end
	end


	def update
		@buyer = Buyer.find(params[:id])
		if @buyer.update_attributes(buyer_params)
			flash[:success] = "Updated"
		else 
			flash[:error] = "Unable to update"
		end
	end

	def edit
		@buyer = Buyer.find_by(params[:id])
	end

	def destroy
		@buyer  = Buyer.find(params[:id])
		@buyer.destroy
	end 

	private
		def buyer_params
			params.require(:buyer).permit(:username, :email, :password, :password_confirmation)
		end

end

app/controllers/daily_trackers_controller.rb
class DailyTrackersController < ApplicationController
	def create
		@daily = current_user.daily_trackers.build(daily_tracker_params)
		@daily.buyer_id = current_user.id
		@daily.dayNumber = 0
		@daily.dailyReportedMealPercentage = 0.0
		if @daily.save
			flash[:success] = 'Welcome to today\'s practice.'
		else 
			flash[:error] = 'Cannot checkIn. Please try again.'
		end
	end

	private
		def daily_tracker_params
			params.require(:checkIn).permit(:dailyCheckIn)
		end

end

app/controllers/nutrition101s_controller.rb
class Nutrition101sController < ApplicationController
	def create
		@nutri = Nutrition101s.new(nutri_params)
		if @nutri.save
			flash[:success] = 'Created Nutrition Suggestion'
		else
			flash[:error] = 'Unable to create Nutrition Suggestion'
		end
	end

	def update
		@nutri = Nutrition101.find(params[:id])
		if @nutri.update_attributes(nutri_params)
			flash[:success] = "Updated Nutrition Suggestion"
		else 
			flash[:error] = "Unable to update yNutrition Suggestion"
		end
	end

	def edit
		@nutri = Nutrition101.find_by(params[:id])
	end

	def destroy
		@nutri  = Nutrition101.find(params[:id])
		@nutri .destroy
	end 

	private 
		def nutri_params
			params.require(:suggestion).permit(:suggestion)
		end
end

app/controllers/overseers_controller.rb
class OverseersController < ApplicationController
	def show
		@seer = Overseer.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
			buyer = Buyer.find_by(email: params[:session][:email].downcase)
			if buyer && buyer.authenticate(params[:session][:password])
				log_in buyer
				redirect_to buyer
			else
				flash.now[:error] = "Invalid LogIn"
				redirect_to root_url
			end
	end

	def destroy
		log_out
		redirect_to root_url
	end
end

app/helpers/app_pages_helper.rb
module AppPagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title (page_title = '')
		base_title = "the2HRDieT" 
		if page_title.empty?
			base_title
		else 
			page_title + " - " + base_title
		end
	end
end

app/helpers/buyer_sessions_helper.rb
module BuyerSessionsHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/daily_trackers_helper.rb
module DailyTrackersHelper
end

app/helpers/nutrition101s_helper.rb
module Nutrition101sHelper
end

app/helpers/overseers_helper.rb
module OverseersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(buyer)
		session[:buyer_id] = buyer.id
	end

	#returns currently logged in user
	def current_user
		if session[:buyer_id]
		 	 @current_user ||= Buyer.find_by(id: session[:buyer_id])
		end
	end

	def logged_in?
		!current_user.nil?
	end

	#logs out current user
	def log_out
		session.delete(:buyer_id)
		@current_user = nil
	end


	#login the overseers
	def overseer_log_in(overseer)
		session[:overseer_id] = overseer.id
	end


	def current_overseer
		if session[:overseer_id]
			@current_overseer ||= Overseer.find_by(id: session[overseer_id])
		end
	end

	def overseer_logged_in?
		!current_overseer.nil?
	end

	def overseer_logged_out
		session.delete(:overseer_id)
		@current_overseer
	end

	
end

app/views/app_pages/_terms.html.erb
<div >
<h4 >Terms and Conditions</h4>
<p>
Please carefully read the following terms and conditions that govern the proper use of our web application and any and all related content provided in the paid and unpaid sections
</p>

<p>
By using our Web Application, you hereby agree to these Terms and Conditions of Use(“Terms and Conditions”). We hereby notify you that we reserve the right in our sole discretion to change, modify, add, remove and update any parts of these Terms and Conditions at any time as we see fit.

You should check these Terms and Conditions on a regular basis and will be notified when changes are made. You agree to the Terms and Conditions after we update them upon your use of this Web Application. If you do not agree with these Terms and Conditions, you must not use this web application and should delete your subscription with us. 
</p>
</div>

<div >
<h4 >Scope of Terms and Conditions</h4>
<p>
Unless indicated otherwise, our Terms and Conditions apply to the use of all content owned and provided by 2hRDieT.herokuapp.com web application.
</p>

</div>

<div >
<h4 >General Terms and Conditions</h4>
<p>
Using this web application, legally binds you to abide by the Terms and Conditions, as though you had signed this document. Using this web application stands as your digital signature, therefore you are legally bound to abide to the Terms and Conditions of Use.
</p>

<p>
If you do not comply, we reserve the right to terminate your account thereby taking away your access privileges to the paid portion of the application. We also ask that you discontinue the use of our unpaid sections of the web application.
</p>

<p>
We may discontinue, modify or alter any portion of the web application(paid and unpaid) without prior notice or liability. This alterations and modifications include but are not limited to 
</p>
<ol>
<li>Restricting the times the Web Application is Available</li>
<li>Restricting the number of users</li>
<li>Terminating access and rights of the user</li>
</ol>

<p>
You agree that terminating or cancelling access and rights may be effected without prior notice. If you cannot comply and do not comply to our Terms and Conditions, you agree that we can immediately terminate your account and delete all user and account related information and bar any access to our application. 
</p>

<p>
You also agree that we shall not be liable for you or any third party cancellation or termination of your access and use of 2hRDieT web application.
</p>

</div>


<div >
<h4 >Requirements for Use of 2hRDieT Service</h4>

<p>
Only persons age 13 years or older can create accounts. Accounts for persons under 13 years old can be created under the name of the legal guardian and should be marked as such. These accounts must be monitored and supervised by a registered healthcare professional such as a Primary Care Physican. 
</p>
</div>

<div >
<h4 >Health Disclaimer</h4>
<p>
This web application provides weight loss and weight management tools to be followed and is only intended to assist in personal weight loss and weight management efforts. 2hRDieT is not a medical organization and we cannot give you medical advice or provide diagnosis. No information and content presented in this web application may be construed as medical advice or be used to provide diagnosis-this is strictly forbidden. In such a case, contact your Physician. The information we provide should not at any time substitute your Physicians’ recommendations, evaluations and treatments unless approved by your Physician. 
You are urged and encouraged to seek your Physicians’ approval before beginning a weight loss program. 
This web application is intended for use by healthy adults. 
The website is not intended for minors, pregnant women, or individuals with any type of active health condition or deemed unhealthy by a Physician to begin a weight loss and exercise regimen.
<p>
</div>

<div >
<h4 > Usage Rules</h4>

<ul>
<li>You shall be authorized to use 2hRDieT for personal, noncommercial use</li>
<li>You shall not collect any information without our legal consent for any scientific research and purposes including commercial gain</li>
<li>You shall follow the set program as it is presented to you and shall validate your participation via the checkIn button and follow the practices in order to track your progress and unlock any accomplishments as the only way to ensure success and long term accomplishment</li>
<li>You shall not share your account, it’s content, this program and any paid services with another individual who is not a paid member for personal use. </li>
<li>Your progress may vary and may require that you modify your content, but not without the consent of your Physician </li>
<li>You may not under any circumstances continue to use 2hRDieT.herokuapp.com if your BMI is below 18.5 and weight drop 5lbs below your recommended height to weight ratio as recommended by medical professionals </li>
<li>You are not authorized to use and must discontinue use if you are under the threat of a medical condition including but not limited to eating disorders- bulimia nervosa, anorexia or exercise disorders. Promptly see your Physician if such a case arises.</li>
</ul>

</div>

<div >
<h4 >Your Account</h4>

<p>As a registered user of the web application you may establish an account(“Account or Dashboard or Lovelies Dashboard”)
Do not reveal you account information to anyone else.
You are solely responsible for maintaining the confidentiality and security of your account and all activities that occur on or through your account and you agree to notify 2hRDieT immediately of any security breech of your account. 
2hRDieT shall not be responsible for any losses arising out of the unauthorized use of your account.
</p>
</div>

<div >
<h4 >Season Pass, Monthly Pass, Legend Pass</h4>
<p>
The prices of our Season, Fortnight and Monthly price are subject to change. You will be notified upon such changes and will be billed according if it applies to your subscription type. These changes in billing will affect users in the following ways:</p>
<ul>

<li>Currently Registers Seasonal Pass users will not be charged for any these changes, you may continue to use the web application without disruption of service as a result of subscription pass change.</li>
<li>New Registering Seasonal Pass users will be charged the new fee upon registration.</li> 
<li>Currently Registered Monthly Pass Users will be billed for the change at their next billing date. The change will be reflected in your account dashboard and your credit card statement.</li>
<li>New Registering Users who select the monthly pass option will be billed to reflect the new billing changes</li>
<li>Current Legend Pass Users will be billed to reflect the change in price at their next billing date. The change will be reflected in your account dashboard and credit card statement</li>
<li>New Users opting for the Legend Pass will be billed to reflect the price change upon opting into the Legend Pass</li>

</div>

<div >
<h4 >Changing Your Payment Plan</h4>

<p>Currently users cannot change their payment plan once the account is activated.</p>
</div>

<div >
<h4 >Privacy</h4>

<p>Please read our privacy policy here</p>

</div>

<div >
<h4 >Termination</h4>
<p>
If you fail or suspect that 2hRDieT have failed to comply with any of the provisions of this agreement, 2hRDieT at it’s sole discretion without notice to you may 
Terminate this agreement and or your account and you will remain liable for amounts due under your Account for the current billing cycle.
2hRDieT reserves the right to modify suspend or discontinue the service or any part of the content thereof at anytime with or without notice to you and 2hRDieT will not be liable to you or to any third party should it exercise such rights
</p>

</div>

<div >

<h4 >WAIVER AND INDEMNITY</h4>

<p>
BY USING THE APP YOU AGREE, TO THE EXTENT PERMITTED BY LAW, TO INDEMNIFY AND HOLD 2hRDieT, ITS DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, AGENTS, CONTRACTORS, PRINCIPALS, AND LICENSORS HARMLESS WITH RESPECT TO ANY CLAIMS ARISING OUT OF YOUR BREACH OF THIS AGREEMENT, YOUR USE OF THE APP AND SERVICES, OR ANY ACTION TAKEN BY 2hRDieT AS PART OF ITS INVESTIGATION OF A SUSPECTED VIOLATION OF THIS AGREEMENT OR AS A RESULT OF ITS FINDING OR DECISION THAT A VIOLATION OF THIS AGREEMENT HAS OCCURRED. THIS MEANS THAT YOU CANNOT SUE OR RECOVER ANY DAMAGES FROM 2hRDieT, ITS DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, AGENTS, CONTRACTORS, PRINCIPALS, AND LICENSORS AS A RESULT OF ITS DECISION TO REMOVE OR REFUSE TO PROCESS ANY INFORMATION OR CONTENT, TO WARN YOU, TO SUSPEND OR TERMINATE YOUR ACCESS TO THE APP SERVICES, OR TO TAKE ANY OTHER ACTION DURING THE INVESTIGATION OF A SUSPECTED VIOLATION OR AS A RESULT OF APPLE'S CONCLUSION THAT A VIOLATION OF THIS AGREEMENT HAS OCCURRED. THIS WAIVER AND INDEMNITY PROVISION APPLIES TO ALL VIOLATIONS DESCRIBED IN OR CONTEMPLATED BY THIS AGREEMENT.
</p>
</div>

<div >
<h4 >Changes</h4>
<p>
2hRDieT reserves the right at any time to modify this Agreement and to impose new or additional terms or conditions on your use of the App and Services. Such modifications and additional terms and conditions will be effective immediately and incorporated into this Agreement. Your continued use of the App and Services will be deemed acceptance thereof.
</p>
</div>

<div >
<h4 >Miscellaneous Terms</h4>
<p>
In any action against us, arising from the use of this web application and web site, the prevailing party shall be entitled to recover all legal expenses incurred in connection with the action, including but not limited to costs, both taxable and non-taxable and reasonable attorney fees.</p>
</div>
</article>

app/views/app_pages/home.html.erb
<% provide(:title, "Welcome") %>
<div id="home-pg">
	<div id="home-opts">
		<h4 class="home-header" id="intro">Introducing the2hRDiet </h4>
		<h4 class="home-header" id="hiw">How it Works </h4>
		<h4 class="home-header" id="food">Food and the Body </h4>
		<h4 class="home-header" id="more">More </h4>
		<h4 class="home-header" id="ideal"> Ideal WeightLoss + Lifetime Management </h4>
	</div>

	<div id="home-opts-content">
		<div id='band'>
		</div>
		<%= image_tag("introClock-01.png", :class => 'homeIcon' )%>
		<div class="explain exp-def" id="intro-explain">
			<p class='home-explain  '> Eating shouldn't be hard </p>
			<p class="home-expl-parag intro-parag">'Diet' simply means the way we eat.  Most diets tell us to eat when we are hungry which we can never really tell anymore - is this hunger, boredom a craving? or not to eat a whole list of foods we barely remember or count as we eat which is exhausting.</p>
			<p class="home-expl-parag">The 2hRdieT takes the frustration out of the most basic thing we all do 'EAT' and makes it enjoyable again. The 2hRDieT allows you to eat every 2 hours. This means that you eat within 2 hours of waking and 2 hours  before going to bed. </p>
			<p class="home-expl-parag">You can eat anything you like, we suggest healthy food, but that's up to you, there aren't any limitations. </p>
		</div>
		<div class="explain" id="hiw-explain">
						<p class='home-explain'> How It Works</p>
			<p class="home-expl-parag intro-parag">The 2hRdieT takes the frustration out of the most basic thing we all do 'EAT' and makes it enjoyable again. The 2hRDieT allows you to eat every 2 hours. </p>
			<p class="home-expl-parag">This means that you eat within 2 hours of waking and 2 hours  before going to bed.You can eat anything you like, we suggest healthy food, but that's up to you, there aren't any limitations. </p>

		</div>
		<div class="explain" id="food-explain">
			<p class='home-explain'> Food and the Body </p>
			<p class="home-expl-parag intro-parag"> Food takes 30minutes to move from our mouths through our guts, stomachs and then intestines(try tracking the time it takes to get the effects of food poisoning ).</p>
			<p class="home-expl-parag"> Once in the intestines, the food is digested and separated in useful(nutritionally rich which means it contains minerals, proteins, carbs, fat compounds that the body processes need to carry out their various chemical reactions to sustain life and the stuff the body doesn't need which is slated for removal from the body. </p>
			<p class="home-expl-parag">It's a beautiful process. </p>

		</div>
		<div class="explain" id="more-explain">
			<p class='home-explain'> More... </p>
			<p class="home-expl-parag intro-parag"> The body usually uses up the resources or food supplied to it in 1-2hrs. How?</p>
			<p class="home-expl-parag"> Using your arms takes up alot of energy, ensuring cells are repaired and are able to carry out their various functions like meiosis or meitosis takes up alot of energy. Walking to your refridgerator or doing something as mundane as picking a nail file off the floor takes up alot of energy, so does singing in the shower, showering itself - scrubbing your body is an involved process. Heck chewing your favorite pineapple+apple gum takes up alot of energy. </p>
			<p class="home-expl-parag">So it's not surprising your body beacons you for more food within a short period of having had a meal, which averages 2 hours. </p>
		</div>
		<div  class="explain" id="ideal-explain">
						<p class='home-explain'>iDeal Weight</p>
			<p class="home-expl-parag intro-parag"> iDeal weight is attainable without torturing yourself... All you have to do is eat every 2 hours. EASY.
			Not doing so is like not putting a full tank of gas in your car and expecting it to run on close of empty fill ups, every other day. It will soon give you up for better pastures. </p>
			<p class="home-expl-parag">Eating every two hours in amazing, first you don't deprive yourself AT ALL and eat everything you enjoy - A FOOD LOVER'S paradise, then you never feel deprived and so don't binge and you let go of the frustration of disatisfaction, that comes with depriving yourself. You are not cranky anymore and you get to explore all food options from the most questionable to the most healthy on your own terms. </p>
			<p class="home-expl-parag">The best part is that you don't have to worry about your weight. You can't overflow a gas tank unless you are being careless and wasteful. Same goes with your body, your body will stop you from eating once you've had enough. This is the way to your iDeal Weight. </p>
		</div>
		<div id='bandtwo'>
		</div>
	</div>
	</div>

		<div class="footer-content"  id="health-policy">
		<p class="hparag" style="margin-top: 125px;">the2hRDieT is a weight loss and weight management tool developed with your wellness in mind. However the2hRDieT is not a medical organization and should not in any event be substituted for one. Therefore we cannot and will not dispense medical advice.</p>

<p  class="hparag">We strongly urge and recommend that you receive medical examinations before starting our practice and during our practice because weight loss can create physical changes that may need to be medically monitored by a healthcare professional.</p>

<p class="hparag" >Monitoring your medical health is especially important for people with pre-existing medical conditions. Our tool is helpful but is not intended to treat any illness or disease.</p>

<p class="hparag">In addition we prohibit participation of children or pregnant women unless monitored and supervised by a primary care physician.</p>

<p  class="hparag">We prohibit participation of any one with an active diagnosis of bulimia nervosa, or individuals whose weight is less that the recommended weight range to height ratio(who are underweight).</p>

 <p class="hparag">If you are being treated for disease or following a therapeutic diet, it is important to show your Physician the2hRDieT tool and follow any recommendations your Physician may make(please look at the Terms and Conditions for additional stipulations).</p>

<p class="hparag"> TOOL is designed for a safe rate of weight loss, it is not to be abused in any way to accelerate weight loss, it is important that you follow the plan and allow your body to make gentle changes and adaptions over time in order to prevent any health complications. Responsibility is a core teaching and building trust with yourself is important for long term wellness. Please adhere to the practices taught and do not abuse the information given by rapidly decreasing your portions, over exercising, eating less that your daily caloric needs.  If you find yourself losing weight faster, you should see a physician and work with them on how you can maintain your recommended weight range.</p>


<p class="hparag">Our goal is to provide a safe and effective way to create habits that promote weight loss and long term weight management. It is extremely important that you adhere to our recommendations as they have been carefully implemented with your wellness in mind. </p>
	</div>

	<div class="footer-content"  id="termsc">
		<%= render 'app_pages/terms' %>
	</div>

	<div class="access-forms" id="signup-form">
		<%= render 'buyers/signup' %>
	</div>

	<div class="access-forms" id="login-form">
		<%= render 'sessions/login' %>
	</div>

</div>

app/views/buyers/_all_buyers.html.erb
<p> all buyers </p>

app/views/buyers/_edit.html.erb
<div id="edit-a">
	<p> Edit Account </p>
	<%= form_for(@buyer, url: buyer_path) do |f| %>


	<label>
<%= f.text_field :username,:required => true %>
<div class="label-text" > username</div>
</label>


<label>
<%= f.email_field :email,:required => true %> 
<div class="label-text" > Email </div>
</label>

<label>
<%= f.password_field :password, :required => true %>
<div class="label-text" > Password </div>
</label>

<label>
<%= f.password_field :password_confirmation, :required => true %>
<div class="label-text" > Password Confirmation </div>
</label>

<%= f.submit "UPDATE", :id => 'update-acct' %>

<% end %>
</div>

app/views/buyers/_signup.html.erb
<%= form_for :buyer, url: start_path do |f| %>


	<label>
<%= f.text_field :username,:required => true %>
<div class="label-text" > username</div>
</label>


<label>
<%= f.email_field :email,:required => true %> 
<div class="label-text" > Email </div>
</label>

<label>
<%= f.password_field :password, :required => true %>
<div class="label-text" > Password </div>
</label>

<label>
<%= f.password_field :password_confirmation, :required => true %>
<div class="label-text" > Password Confirmation </div>
</label>

<%= f.submit "START" %>


<% end %>

app/views/buyers/show.html.erb
<% provide(:title, "Dashboard") %>
<div id="buyer-dashboard">
	<div id="buyer-logo">
		<p id="username"> <%= current_user.username %>'s <br> 2hRDieT</p>
	</div>

	<% if current_user.new_session %>
		<p> <% @endDate =  Date.today + 22 %> </p>
		<p> <% @startDate =  Date.today %> </p>
		<p> <% @daysBetween = (@startDate...@endDate).count %> </p>
		<% if current_user.first_signup %>
			<p><% @num = current_user.session_num + 0 %></p>
			<% current_user.first_signup = false %> 
		<%else%>
			<p><% @num = current_user.session_num + 1 %></p>
		<%end%>

		<% BuyerSession.new(buyer_id: current_user.id, startDate: @startDate, endDate: @endDate, sessionNum: @num).save %>
		<p> <%= @daysBetween   %> </p>
	<% end %>

	<p> <%= @current_day = ((current_user.buyer_sessions.find_by(sessionNum: @num).startDate)...Date.today).count  %> </p>

	<%= image_tag("2hrdiet-01.png", :id => 'dashIcon' )%>

	<div id="updates">
		<p> Click the CheckIn Button to generate today's meal times. </p>
		<%= form_for :checkIn, url: create_daily_tracker_path do |f| %>
		<%= f.hidden_field :dailyCheckIn %>
			<%= f.submit 'CheckIn', :id=>"dailyCheckIn" %>
		<% end %>
	</div>


	<div id="current_day">
		<div id="day_tracker">
			<p> Current Day </p>
			<div class="dayNum"><p><%= @current_day %>/21</p></div>
		</div>

		<div id="main_content">
	
			<p class="dash-main"><button class="mealCheck"> Report Meal </button>Mealtime </p>
			<p class="dash-main"> <button class="mealCheck"> Reported Meal </button>Mealtime </p>
		</div>

		<div id="meal-sug">
			<div class="meal-sug-icons">
			</div>
			<div class="meal-sug-content">
			<p> Meal Suggestions </p>
			<% if @nutrition.count > 1 %>
				<% @randomRecord = rand(1..@nutrition.count)%>
			<% else %>
				<p class="nutri-sug"> The best way to lose weight and keep it off if to eat every 2hours </p>
			<% end %>
			
		</div>
		</div>
	</div>

	<div id="days">
		<% for x in 0..21 %>
			<div class="day-data"><p class="day-label">Day<%=x%></p></div>
		<%end%>
	</div>


</div>

<div class= "acct-forms" id="edit-acct-form">
	<%= render 'buyers/edit' %>

</div>

<div class="acct-forms" id="contect-acct-form">

</div>

	<div id="settings">
		<p class="acct-bttn" id="edit-acct"> Edit Password </p>
		<p> <%= link_to "Log out", logout_path, method: :delete %> </p>
	</div>

app/views/overseers/show.html.erb
<% provide(:title, @seer)%>
<div id="seer">
	<p> Show Diet Data </p>
</div>